import argparse
from pathlib import Path
from src.utils.io import load_config, save_json
from src.utils.logging import log_orchestrator_event

from src.agents.planner_agent import PlannerAgent
from src.agents.data_agent import DataAgent
from src.agents.insight_agent import InsightAgent
from src.agents.evaluator_agent import EvaluatorAgent
from src.agents.creative_agent import CreativeAgent


def generate_full_report(insights, creatives):
    lines = []
    lines.append("# ROAS Performance Diagnostic Report")
    lines.append("*Generated by the Agentic Facebook Performance Analyst System*\n")

    lines.append("## Key Insights\n")
    for i in insights:
        lines.append(
            f"- **{i['metric'].upper()}** → {i['hypothesis']} "
            f"(Severity: `{i['severity']}`, Δ={round(i['delta'],4)}, "
            f"Change={round(i['evidence']['relative_change_pct'],2)}%)"
        )

    lines.append("\n## Creative Recommendations\n")
    for c in creatives:
        lines.append(f"### Campaign: {c['campaign']}")
        lines.append(f"- **Angle:** {c['angle']}")
        lines.append(f"- **Why this works:** {c['why_this_angle']}")
        lines.append(f"- **Hooks:** {', '.join(c['hooks'])}")
        lines.append(f"- **CTAs:** {', '.join(c['ctas'])}\n")

    lines.append("---\n*End of Report*")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("query")
    parser.add_argument("--config", default="config/config.yaml")
    args = parser.parse_args()

    cfg = load_config(args.config)

    try:
        log_orchestrator_event("Starting pipeline", {"query": args.query})

        planner = PlannerAgent(cfg)
        plan = planner.decompose(args.query)

        data_agent = DataAgent(cfg)
        summary = data_agent.summarize({})

        insight_agent = InsightAgent(cfg)
        insights = insight_agent.propose(summary, plan)

        evaluator = EvaluatorAgent(cfg)
        validated = evaluator.validate(insights, summary)

        creative_agent = CreativeAgent(cfg)
        creatives = creative_agent.generate(summary, validated)

        save_json(validated, cfg["outputs"]["insights"])
        save_json(creatives, cfg["outputs"]["creatives"])

        report = generate_full_report(validated, creatives)
        Path(cfg["outputs"]["report"]).write_text(report, encoding="utf-8")

        log_orchestrator_event("Pipeline complete")
        print("✔ Run complete. Outputs stored in reports/")

    except Exception as e:
        log_orchestrator_event("Pipeline Error", {"error": str(e)})
        Path(cfg["outputs"]["report"]).write_text(
            f"# Partial Report\nError occurred:\n\n`{e}`",
            encoding="utf-8"
        )
        print("❌ Run failed — check logs/")


if __name__ == "__main__":
    main()
